const fs = require('fs');
const path = require('path');

// Load .env if present so that local development can use it
require('dotenv').config({ path: path.join(__dirname, '../.env') });

// Get configuration from environment variables (possibly loaded from .env) or use defaults
const API_URL = process.env['API_URL'] || 'http://localhost:8080';
const SOCKET_URL = process.env['SOCKET_URL'] || 'http://localhost:8080';
const GOOGLE_MAPS_API_KEY = process.env['GOOGLE_MAPS_API_KEY'] || 'AIzaSyC55ytCYBbBKrqbm10kHQBmwXNyYoxCogE';
const GOOGLE_MAPS_MAP_ID = process.env['GOOGLE_MAPS_MAP_ID'] || 'a576f9d07a3eb6be92fc5da3';
const RECAPTCHA_SITE_KEY = process.env['RECAPTCHA_SITE_KEY'] || '';

// Determine target environment from APP_ENV or NODE_ENV
const APP_ENV = (process.env.APP_ENV || process.env.NODE_ENV || 'development').toLowerCase();
const isTargetProduction = APP_ENV === 'production';

// Create environment configuration with all required properties
const createEnvConfig = (production = false) => `// Auto-generated by scripts/generate-env.js (APP_ENV=${APP_ENV})\nexport const environment = {\n  production: ${production},\n  apiUrl: '${API_URL}',\n  apiBaseUrl: '${API_URL}/auth',\n  apiBackendUrl: '${API_URL}',\n  socketUrl: '${SOCKET_URL}',\n  apiKeyGoogleMaps: '${GOOGLE_MAPS_API_KEY}',\n  mapsMapId: '${GOOGLE_MAPS_MAP_ID}',\n  recaptchaSiteKey: '${RECAPTCHA_SITE_KEY}'\n};\n`;

const envPath = path.join(__dirname, '../src/environments/environment.ts');
const envProdPath = path.join(__dirname, '../src/environments/environment.prod.ts');

// Ensure environments directory exists
const envDir = path.dirname(envPath);
if (!fs.existsSync(envDir)) {
  fs.mkdirSync(envDir, { recursive: true });
}

// Always write environment files to ensure they're up to date
// environment.ts reflects the target APP_ENV (production=true if APP_ENV=production)
fs.writeFileSync(envPath, createEnvConfig(isTargetProduction));
console.log(`Generated environment.ts (production: ${isTargetProduction})`);

// environment.prod.ts is always production=true
fs.writeFileSync(envProdPath, createEnvConfig(true));
console.log('Generated environment.prod.ts (production: true)');

// Helpful log for debugging where values came from
const envFile = fs.existsSync(path.join(__dirname, '../.env')) ? '.env' : 'process environment';
console.log(`Env values loaded from: ${envFile}`);

// Warn if defaults are used for key values (helps catch missing CI variables)
const defaultsUsed = [];
if (!process.env['API_URL']) defaultsUsed.push('API_URL');
if (!process.env['GOOGLE_MAPS_API_KEY']) defaultsUsed.push('GOOGLE_MAPS_API_KEY');
if (defaultsUsed.length > 0) {
  console.warn(`Warning: using default values for: ${defaultsUsed.join(', ')}. Set these in your CI or in .env to avoid defaults.`);
}

if (!RECAPTCHA_SITE_KEY) {
  console.warn('Warning: RECAPTCHA_SITE_KEY is empty. The login will be sent without a captcha token.');
}
